# Generated by Django 3.2 on 2024-02-04 17:52

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('condo', 'Condo')], max_length=20)),
                ('bedrooms', models.IntegerField(choices=[(1, '1 Bedroom'), (2, '2 Bedroom'), (3, '3 Bedroom'), (4, '4 Bedroom'), (5, '5 Bedroom'), (6, '6 Bedroom'), (7, '7 Bedroom'), (8, '8 Bedroom')], validators=[django.core.validators.MinValueValidator(1)])),
                ('bed', models.IntegerField(choices=[(1, '1 Bed'), (2, '2 Bed'), (3, '3 Bed'), (4, '4 Bed'), (5, '5 Bed'), (6, '6 Bed'), (7, '7 Bed'), (8, '8 Bed'), (9, '9 Bed'), (10, '10 Bed'), (11, '11 Bed')], validators=[django.core.validators.MinValueValidator(1)])),
                ('bathrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('rent_period', models.CharField(choices=[('day', 'DAY'), ('month', 'MONTH'), ('year', 'YEAR')], max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('available_from', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 2, 4))])),
                ('is_featured', models.BooleanField(default=False)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_furnished', models.BooleanField(default=False)),
                ('heating_system', models.CharField(blank=True, choices=[('central', 'Central Heating'), ('electric', 'Electric Heating'), ('gas', 'Gas Heating')], max_length=20, null=True)),
                ('cooling_system', models.CharField(blank=True, choices=[('central', 'Central Cooling'), ('split', 'Split System Cooling')], max_length=20, null=True)),
                ('parking_spaces', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_security_system', models.BooleanField(default=False)),
                ('amenities', models.ManyToManyField(blank=True, to='property.Amenity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='property.property')),
            ],
        ),
    ]
